name: Android (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile Shader
      working-directory: Shader
      run: ../Kinc/make android -g vulkan --compile
    - name: Compile Texture
      working-directory: Texture
      run: ../Kinc/make android -g vulkan --compile
    - name: Compile MultiWindow
      working-directory: MultiWindow
      run: ../Kinc/make android -g vulkan --compile
    - name: Compile ComputeShader
      working-directory: ComputeShader
      run: ../Kinc/make android -g vulkan --compile
    - name: Compile TextureArray
      working-directory: TextureArray
      run: ../Kinc/make android -g vulkan --compile
    - name: Compile ShaderG5
      working-directory: ShaderG5
      run: ../Kinc/make android -g vulkan --compile
