name: FreeBSD (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Get Submodules
      run: ./get_dlc
    - name: Get the FreeBSD-submodule
      run: git -C Kinc submodule update --init Tools/freebsd_x64
    - name: Compile in FreeBSD VM
      id: build
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        copyback: false
        mem: 2048
        prepare: pkg install -y bash alsa-lib libXinerama mesa-libs libXi xorg-vfbserver libXrandr libXi libXcursor evdev-proto libinotify ImageMagick7-nox11 libxkbcommon
        run: |
          echo " * Compile Shader"
          cd Shader
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile Texture"
          cd Texture
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile MultiWindow"
          cd MultiWindow
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile ComputeShader"
          cd ComputeShader
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile TextureArray"
          cd TextureArray
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile ShaderG5"
          cd ShaderG5
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 00_empty"
          cd 00_empty
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 01_triangle"
          cd 01_triangle
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 02_matrix"
          cd 02_matrix
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 03_colored_cube"
          cd 03_colored_cube
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 04_textured_cube"
          cd 04_textured_cube
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 05_camera_controls"
          cd 05_camera_controls
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 06_render_targets"
          cd 06_render_targets
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 07_multiple_render_targets"
          cd 07_multiple_render_targets
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 08_float_render_targets"
          cd 08_float_render_targets
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 09_depth_render_targets"
          cd 09_depth_render_targets
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 10_cubemap"
          cd 10_cubemap
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 11_instanced_rendering"
          cd 11_instanced_rendering
          ../Kinc/make freebsd -g opengl --compile
          cd ..
          echo " * Compile 12_set_render_target_depth"
          cd 12_set_render_target_depth
          ../Kinc/make freebsd -g opengl --compile
          cd ..
