name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get LunarG key
      run: wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
    - name: Get LunarG apt sources
      run: sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev vulkan-sdk libwayland-dev wayland-protocols libxkbcommon-dev ninja-build --yes --quiet

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile Shader
      working-directory: Shader
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile Texture
      working-directory: Texture
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile MultiWindow
      working-directory: MultiWindow
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile ComputeShader
      working-directory: ComputeShader
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile TextureArray
      working-directory: TextureArray
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile ShaderG5
      working-directory: ShaderG5
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 08_float_render_targets
      working-directory: 08_float_render_targets
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 10_cubemap
      working-directory: 10_cubemap
      run: ../Kinc/make linux -g vulkan --compile
    - name: Compile 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: ../Kinc/make linux -g vulkan --compile
